### PR TITLE
Add support and tests for the schema sql format

### LINKED ISSUE #8: Structure Dump & Load
When the `ActiveRecord::Base.schema_format` is set to `:sql`, a structure dump is used. Modern Rails also has a structure load. Some nuances of the implementation support `DB_STRUCTURE` environment variable with a fallback to `structure.sql`. I even noticed how this task even asks the DatabaseTask module for the #db_dir too. Interesting.

### PR DESCRIPTION
**Pull request by hmadison**
Resolves #8

cc @metaskills

### CODE REVIEW

**Comment by metaskills** [comment]
Did you notice the binding.pry failures?

**Comment by hmadison** [comment]
yeah fixed.

**Comment by metaskills** [comment]
I really like the way that tests reads. Amazing how fat `SecondBase.on_base` is getting too.

**Comment by hmadison** [comment]
@metaskills Its a side effect of the global state we need to dig into to get this to work. I don't think there is a easy way to fix it unless we got stuff upstreamed.

**Comment by metaskills** [comment]
Yea... I don't have issues with it... was just wondering if there were downsides if we consider `on_base` public. I'm not seeing anything but will think about it more.

**Pull request merged**
