### PR TITLE
Rails 5.1 support

### PR DESCRIPTION
**Pull request by hmadison**

### CODE REVIEW

**Comment by GuskiS** [comment]
Tests seem to be failing. Could this be something to do that Rails 5.1 uses Arel 8.0.0.0?

**Comment by hmadison** [comment]
No, this is a config loading issue.

**Comment by metaskills** [comment]
Hmm, I recently got [an issue](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/588) on the SQL Server adapter about configs and loading under v5 and upward for ActiveRecord gems. It goes back to this Rails core issue. https://github.com/rails/rails/issues/23589

I wonder if that is related?

**Comment by GuskiS** [comment]
Are these related #45 ?

**Pull request closed without merging**
