### PR TITLE
add db:structure:dump command

### PR DESCRIPTION
**Pull request by shqear93**
### Description

Add `db:structure:dump` to the list of supported rake tasks

### Changes

I added new task `dump` to the namespace `structure`
I added `structure:dump` to the list the task enhancements `task.enhance`

### JIRA Ticket

nop!

### Screenshots

no screenshots

### Notes

nop!

### CODE REVIEW

**Comment by metaskills** [comment]
Thanks for this! I put some commits to master and another I am working on locally to get the tests passing on Rails v5 & upwards. I'll tag ya when that's done so we can rebase and get this merged.

**Comment by shqear93** [comment]
Ok bro, thanks for the update

**Comment by shqear93** [comment]
@metaskills just a reminder 🍕

**Comment by metaskills** [comment]
Merged to master. Prepared for v2.2.0. But having gem push issues. 

@hmadison Would you mind seeing if you can do a gem push?

**Comment by hmadison** [comment]
@metaskills https://rubygems.org/gems/secondbase/versions/2.2.0

**Comment by metaskills** [comment]
Thank you!

**Pull request merged**
