### PR TITLE
Fix db:second_base:migrate

### PR DESCRIPTION
**Pull request by misteral**
Fix for #42

### CODE REVIEW

**Comment by metaskills** [comment]
Am I right in understanding that if you run `$ bundle exec rake db:migrate` it works? If so, it could be said that even tho we expose these mirrored tasks, we may only truly support them when they are run automatically as part of the parent. Thoughts @hmadison? Would this open the door for more of these?

**Comment by hmadison** [comment]
We should add this to every secondbase task. We don't have coverage on this and I believe changed from 4 to 5. 

Outside of that point, this change looks good to me. @misteral would you be able to add a test to ensure this keeps functioning properly?

**Comment by misteral** [comment]
@hmadison Yes try to do this, on the week.  
@metaskills 
> Am I right in understanding that if you run $ bundle exec rake db:migrate it works?
no, not work.

**Comment by misteral** [comment]
@hmadison Hi, I looks into tests and I do not found the point where I can add configuration asset at the time I had. I add db:load_config for all tasks.

**Comment by metaskills** [comment]
Just published v2.1.3 with this change. Thanks so much for the back and forth and putting time into helping us! Much appreciated.

**Pull request merged**
